In [1]:
import numpy as np 

In [6]:
list= np.round(np.random.uniform(15,35,30),2)
list


array([17.49, 21.86, 19.06, 21.62, 26.63, 18.69, 22.88, 23.79, 31.88,
       31.73, 20.38, 17.96, 16.73, 24.2 , 20.95, 25.38, 32.94, 15.95,
       20.11, 17.37, 19.33, 22.93, 15.76, 18.85, 27.02, 17.22, 20.47,
       30.64, 27.43, 34.58])

In [7]:
# nhiệt độ trung bình 
mean = np.mean(list)
mean

np.float64(22.727666666666668)

In [12]:
max_temp_day = np.argmax(list) + 1  # +1 vì chỉ số bắt đầu từ 0
min_temp_day = np.argmin(list) + 1

# Tính sự chênh lệch giữa các ngày liên tiếp
temp_diff = np.abs(np.diff(list))
max_diff_day = np.argmax(temp_diff) + 1  # Ngày có sự thay đổi nhiệt độ lớn nhất

print(f"Day with highest temperature: Day {max_temp_day}")
print(f"Day with lowest temperature: Day {min_temp_day}")
print(f"Day with the greatest temperature change: Day {max_diff_day}")

Day with highest temperature: Day 30
Day with lowest temperature: Day 23
Day with the greatest temperature change: Day 17


In [10]:
thap_nhat = np.argmin(list)+1
thap_nhat

np.int64(23)

nhiệt độ cao nhất 


In [16]:
nhiet_do_cao_hon_20 = list[list>20] 
nhiet_do_cao_hon_20

array([21.86, 21.62, 26.63, 22.88, 23.79, 31.88, 31.73, 20.38, 24.2 ,
       20.95, 25.38, 32.94, 20.11, 22.93, 27.02, 20.47, 30.64, 27.43,
       34.58])

In [19]:
print("Nhiệt độ của ngày 5 là ", list[4])
print("Nhiệt độ của ngày 10 là", list[9])
print("Nhiệt độ của ngày 15 là", list[14])
print("Nhiệt độ của ngày 20 là", list[15])
print("Nhiệt độ của ngày 25 là", list[24])

Nhiệt độ của ngày 5 là  26.63
Nhiệt độ của ngày 10 là 31.73
Nhiệt độ của ngày 15 là 20.95
Nhiệt độ của ngày 20 là 25.38
Nhiệt độ của ngày 25 là 27.02


In [21]:
# các ngày có nhiệt độ trên trung bình là 
nhiet_do = list[list > mean]
nhiet_do

array([26.63, 22.88, 23.79, 31.88, 31.73, 24.2 , 25.38, 32.94, 22.93,
       27.02, 30.64, 27.43, 34.58])

In [22]:
print("nhiệt độ của ngày chẵn là", list[::2])
print("Nhiệt độ của ngày lẻ là:", list[1::2])

nhiệt độ của ngày chẵn là [17.49 19.06 26.63 22.88 31.88 20.38 16.73 20.95 32.94 20.11 19.33 15.76
 27.02 20.47 27.43]
Nhiệt độ của ngày lẻ là: [21.86 21.62 18.69 23.79 31.73 17.96 24.2  25.38 15.95 17.37 22.93 18.85
 17.22 30.64 34.58]
